name: aluno_crud_app
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  cupertino_icons: ^1.0.0
  dio: ^3.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
